name: Fineract Publish to DockerHub
on:
  push:
    branches:
      - develop
    tags:
      - 1.*
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}
      FINERACT_VERSION: "1.9.0"
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          ref: '1.9.0'
          
      - name: Set up JDK 17
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4
        with:
          java-version: '17'
          distribution: 'zulu'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
        
      - name: Build and Push the Apache Fineract image
        run: |
          ./gradlew --no-daemon --console=plain :fineract-provider:jib -x test -x cucumber \
          -Djib.to.auth.username=${{secrets.DOCKER_USER}} \
          -Djib.to.auth.password=${{secrets.DOCKER_PASSWORD}} \
          -Djib.from.platforms=linux/amd64,linux/arm64 \
          -Djib.to.image=${{ secrets.DOCKER_ORGANIZATION }}/fineract \
          -Djib.to.tags=${FINERACT_VERSION},latest
